name: test
on:
on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Test
        run: go test ./...
